# Living Room Light Groups
# These groups enable unified control of living room lights via voice assistants
# (Alexa, Siri, Google Assistant) and automation
# Uses the light group integration: https://www.home-assistant.io/integrations/light.group/

- platform: group
  name: Living Room Lamps
  unique_id: living_room_lamps_group
  entities:
    - light.living_room_hue_iris
    - light.living_room_floor_lamp_2
    - light.living_room_floor_lamp
    - light.living_room_tv_light

- platform: group
  name: Living Room Lights
  unique_id: living_room_lights_group
  entities:
    - light.living_room_ceiling
    - light.living_room_tv_light
    - light.living_room_floor_lamp_2
    - light.living_room_floor_lamp
    - light.living_room_hue_iris
