- alias: Run Goodnight Routine by Person or Device
  id: goodnight_by_person_or_device
  trigger:
    - platform: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: goodnight_routine
        event_response: ResponseYes
  variables:
    person_id_map:
      amzn1.ask.person.AMBPQ6J5RMQDHF7GPGGFG7NNTUVCX4AIF2ESJAZGCTVXA5WUGKQGAXIHPX42QU5E3HIKDX2JB56242FAT3CY3Q4AZLMZVA3LB2C7AAHVHOFXVHZZ5KWGKQK2XRXNIASWK5YOIN4Y: "ankit"
    responder: "{{ person_id_map.get(trigger.event.data.event_person_id, 'unknown') }}"
    device_matched: >-
      {{ trigger.event.data.source == 'media_player.bedroom_echo' }}
  condition:
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ responder != 'unknown' }}"
        - condition: template
          value_template: "{{ device_matched }}"
  action:
    - service: script.shared_bedroom_bedtime_routine