alias: "Litterbot Bin Emptied"
id: "litterbot_bin_emptied"
description: "Turn light green when bin is emptied (count resets to 0)"
trigger:
  - platform: state
    entity_id: sensor.basement_pantry_shitbot_cleans_in_bin
    to: "0"
condition:
  # Only trigger if previous state was > 0 (actual reset, not startup)
  - condition: template
    value_template: "{{ trigger.from_state.state | int(0) > 0 }}"
action:
  # Turn light green as visual indicator
  - service: light.turn_on
    target:
      entity_id: light.basement_pantry_shitbot
    data:
      rgb_color: [0, 255, 0]
      brightness: 255
  - service: notify.adults
    data:
      title: "🟢 ShitBot Reset"
      message: "Bin emptied! Counter reset to 0."
  # Turn off the green light after 5 minutes
  - delay:
      minutes: 5
  - service: light.turn_off
    target:
      entity_id: light.basement_pantry_shitbot
mode: single
