alias: "Litterbot Clean Cycles Alert"
id: "litterbot_clean_cycles_alert"
trigger:
  - platform: template
    value_template: >-
      {% set cycles = states('sensor.basement_pantry_shitbot_cleans_in_bin') | int(0) %}
      {% set threshold = states('input_number.litterbot_clean_cycles_threshold') | int(10) %}
      {{ cycles >= threshold and cycles > 0 }}
condition: []
action:
  - service: script.alexa_announce_router
    data:
      message: "ShitBot needs to be cleaned."
  - service: notify.mobile_app_7b4b3d84_ce9d_418e_ad95_576581ee855e
    data:
      title: "Litterbot bin"
      message: >-
        ShitBot has {{ states('sensor.basement_pantry_shitbot_cleans_in_bin') }}
        clean cycles in the bin. Time to empty it.
  - service: notify.mobile_app_6edede162518e0a8
    data:
      title: "Litterbot bin"
      message: >-
        ShitBot has {{ states('sensor.basement_pantry_shitbot_cleans_in_bin') }}
        clean cycles in the bin. Time to empty it.
mode: single
