- alias: "Laundry - Transfer Ownership When Washer Available"
  id: "laundry_transfer_ownership_on_washer_available"
  description: "Transfer dryer ownership when washer becomes available (load removed)"
  trigger:
    - platform: state
      entity_id: input_select.washer_owner
      to: "Unknown"
  condition:
    - condition: template
      value_template: "{{ trigger.from_state.state != 'Unknown' }}"
    - condition: template
      value_template: "{{ is_state('input_select.dryer_owner', 'Unknown') }}"
    - condition: state
      entity_id: binary_sensor.dryer_vibration
      state: "on"
  action:
    - variables:
        previous_washer_owner: "{{ trigger.from_state.state }}"
    - service: input_select.select_option
      target:
        entity_id: input_select.dryer_owner
      data:
        option: "{{ previous_washer_owner }}"
    - service: script.alexa_announce_router
      data:
        message: "{{ previous_washer_owner }}, thank you for moving the clothes to the dryer!"
        audience: "adults"
    - service: notify.adults
      data:
        title: "Load Transferred"
        message: "{{ previous_washer_owner }} moved their clothes to the dryer."
        data:
          tag: load_transferred
  mode: single
