- alias: "Laundry - Nagging Reminder"
  id: "laundry_nagging"
  description: "Nag load owner to move clothes to dryer with escalating frequency"
  trigger:
    - platform: state
      entity_id: input_boolean.laundry_nag_enabled
      to: "on"
  condition: []
  action:
    - repeat:
        while:
          - condition: state
            entity_id: input_boolean.laundry_nag_enabled
            state: "on"
        sequence:
          - variables:
              owner: "{{ states('input_select.washer_owner') }}"
              washer_stopped: "{{ states('input_datetime.washer_stopped_time') }}"
              washer_stopped_timestamp: "{{ as_timestamp(washer_stopped) }}"
              snooze_until: "{{ states('input_datetime.laundry_nag_snooze_until') }}"
              snooze_until_timestamp: "{{ as_timestamp(snooze_until) }}"
              is_snoozed: >
                {{ snooze_until_timestamp is not none and now().timestamp() < snooze_until_timestamp }}
              minutes_elapsed: >
                {% if washer_stopped_timestamp is not none and washer_stopped_timestamp > 0 %}
                  {{ ((now().timestamp() - washer_stopped_timestamp) / 60) | int }}
                {% else %}
                  0
                {% endif %}
              is_adult_load: >
                {{ owner in ['Ankit', 'Danielle', 'Ankit+Danielle', 'Mixed'] }}
              is_kid_load: >
                {{ owner in ['Zoe', 'Max', 'Aiden'] }}
              owner_is_home: >
                {% if owner == 'Zoe' %}
                  {{ is_state('person.zoe', 'home') }}
                {% elif owner == 'Max' %}
                  {{ is_state('person.max', 'home') }}
                {% elif owner == 'Aiden' %}
                  {{ is_state('person.aiden', 'home') }}
                {% else %}
                  true
                {% endif %}
              should_escalate: >
                {{ is_adult_load or (is_kid_load and owner_is_home) }}
              washer_is_running: >
                {{ (state_attr('sensor.washer_running_current_consumption', 'value') | float(0)) > (states('input_number.washer_idle_threshold') | float(0)) }}
              nag_interval: >
                {% if should_escalate and minutes_elapsed >= 20 %}
                1
                {% else %}
                5
                {% endif %}
              escalation_msg: >
                {% if should_escalate and minutes_elapsed >= 20 %}
                  It's been {{ minutes_elapsed }} minutes! The clothes are getting musty!
                {% else %}
                  Please move them soon to avoid mildew.
                {% endif %}
          - if:
              - condition: template
                value_template: "{{ not is_snoozed and not washer_is_running }}"
            then:
              - service: script.alexa_announce_router
                data:
                  message: "{{ owner }}, reminder: move your clothes to the dryer. {{ escalation_msg }}"
                  audience: "adults"
              - service: script.laundry_notification_router
                data:
                  title: "Laundry Reminder"
                  message: "{{ owner }}: Move clothes to dryer! {{ escalation_msg }}"
                  owner: "{{ owner }}"
                  mode: "nag"
                  tag: "laundry_nag"
                  actions:
                    - action: "SNOOZE_LAUNDRY_NAG"
                      title: "Snooze 30min"
            else:
              # Washer is running again - pause nagging
              # This handles cases where clothes went back in or new load started
              - service: script.alexa_announce_router
                data:
                  message: "{{ owner }}, nagging paused. The washer is running again."
                  audience: "adults"
          - delay:
              minutes: "{{ nag_interval | int }}"
  mode: single
