alias: "Litterbot Nagging Reminder"
id: "litterbot_nagging"
trigger:
  - platform: state
    entity_id: binary_sensor.basement_pantry_shitbot_problem
    to: "on"
  - platform: state
    entity_id: input_boolean.litterbot_nag_enabled
    to: "on"
condition: []
action:
  - repeat:
      while:
        - condition: state
          entity_id: binary_sensor.basement_pantry_shitbot_problem
          state: "on"
        - condition: state
          entity_id: input_boolean.litterbot_nag_enabled
          state: "on"
      sequence:
        - variables:
            interval_minutes: "{{ states('input_number.litterbot_nag_interval') | int(30) }}"
            snooze_until: "{{ states('input_datetime.litterbot_nag_snooze_until') }}"
            home_snooze_enabled: "{{ is_state('input_boolean.litterbot_nag_snooze_until_home', 'on') }}"
            home_snooze_person: >-
              {% set candidate = states('input_text.litterbot_nag_snooze_until_home_person') %}
              {% if candidate in states %}
                {{ candidate }}
              {% else %}
                person.ankit_aggarwal
              {% endif %}
            home_snoozed: >-
              {{ home_snooze_enabled and not is_state(home_snooze_person, 'home') }}
            time_snoozed: >-
              {{ snooze_until not in ['unknown', 'unavailable', 'none', ''] and
                 as_timestamp(snooze_until) > as_timestamp(now()) }}
            snoozed: "{{ time_snoozed or home_snoozed }}"
            nag_message: >-
              {% set camden_nags = [
                "Camden grumbles: still broken.",
                "Camden: this is unacceptable.",
                "Camden: we need service.",
                "Camden: this is your job.",
                "Camden: restroom access denied.",
                "Camden: shame."
              ] %}
              {% set poe_nags = [
                "Poe: oh. is this bad? fix it.",
                "Poe: wait, what? fix it.",
                "Poe: is that the bathroom? make it work.",
                "Poe: I don't get it. fix it.",
                "Poe: are we okay? fix it.",
                "Poe: please make it stop."
              ] %}
              {{ [camden_nags | random, poe_nags | random] }}

        - if:
            - condition: template
              value_template: "{{ not snoozed }}"
          then:
            - service: notify.mobile_app_7b4b3d84_ce9d_418e_ad95_576581ee855e
              data:
                message: "💩 Litterbot is STILL busted. Cats are circling. Send help."
                title: "NAG: Fix the Litterbot"
                data:
                  persistent: true
                  ttl: 0
                  priority: high
                  tag: litterbot_nag

            - service: notify.mobile_app_6edede162518e0a8
              data:
                message: "💩 Litterbot is STILL busted. Cats are circling. Send help."
                title: "NAG: Fix the Litterbot"
                data:
                  persistent: true
                  ttl: 0
                  priority: high
                  tag: litterbot_nag

        - delay:
            minutes: "{{ interval_minutes }}"
mode: single
