- alias: "Litterbot Usage Notification"
  id: "litterbot_usage_notification"
  description: "Notify when the Litterbot is used with current cycle count"
  trigger:
    - platform: state
      entity_id: sensor.basement_pantry_shitbot_cleans_in_bin
  condition:
    - condition: template
      value_template: >-
        {{ trigger.to_state.state | int(0) > trigger.from_state.state | int(0) }}
  action:
    - service: notify.adults
      data:
        title: "ðŸ± ShitBot Used"
        message: >-
          Cycle {{ states('sensor.basement_pantry_shitbot_cleans_in_bin') }} since last clean.
  mode: single
