- alias: "Laundry - Dryer Finished"
  id: "laundry_dryer_finished"
  description: "Alert dryer owner when dryer vibration stops"
  trigger:
    - platform: state
      entity_id: binary_sensor.dryer_vibration
      to: "off"
      for:
        minutes: 2
  condition:
    - condition: template
      value_template: "{{ not is_state('input_select.dryer_owner', 'Unknown') }}"
  action:
    - service: input_datetime.set_datetime
      target:
        entity_id: input_datetime.dryer_stopped_time
      data:
        datetime: "{{ now().isoformat() }}"
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.dryer_door_opened_since_stop
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.dryer_nag_enabled
    - variables:
        owner: "{{ states('input_select.dryer_owner') }}"
    - service: script.alexa_announce_router
      data:
        message: "{{ owner }}, the dryer has finished. Please check if your clothes are dry."
        audience: "adults"
    - service: script.laundry_notification_router
      data:
        title: "Dryer Finished"
        message: "{{ owner }}, please check if your clothes are dry and open the dryer door!"
        owner: "{{ owner }}"
        mode: "nag"
        tag: "dryer_finished"
        actions: []
  mode: single
