- alias: "Laundry - Dryer Started"
  id: "laundry_dryer_started"
  description: "Stop nagging when dryer vibration is detected"
  trigger:
    - platform: state
      entity_id: binary_sensor.dryer_vibration
      to: "on"
      for:
        seconds: 30
  condition:
    - condition: state
      entity_id: input_boolean.laundry_nag_enabled
      state: "on"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.laundry_nag_enabled
    - variables:
        owner: "{{ states('input_select.washer_owner') }}"
    - service: script.alexa_announce_router
      data:
        message: "{{ owner }}, thank you for moving the clothes to the dryer!"
        audience: "adults"
    - service: notify.adults
      data:
        title: "Dryer Started"
        message: "{{ owner }} moved the clothes to the dryer. Good job!"
        data:
          tag: dryer_started
    - service: input_select.select_option
      target:
        entity_id: input_select.washer_owner
      data:
        option: "Unknown"
  mode: single
