alias: "Litterbot Nagging Reminder"
id: "litterbot_nagging"
trigger:
  - platform: time_pattern
    minutes: "/10"
condition:
  - condition: state
    entity_id: binary_sensor.litterbot
    state: "on"
  - condition: state
    entity_id: input_boolean.litterbot_nag_enabled
    state: "on"
action:
  - repeat:
      for_each:
        
        - media_player.bedroom_echo
        - media_player.living_room_alexa
        - media_player.kitchen_echo
        - media_player.zoe_s_room
        - media_player.kitchen_2
        - media_player.living_room_soundbar_2
        - media_player.aiden_s_echo_show
        - media_player.ankit_s_sonos_arc
        - media_player.max_s_bedroom_echo
      sequence:
        - service: notify.alexa_media
          data:
            target: "{{ repeat.item }}"
            message: >
              {% set nags = [
                "Friendly reminder from the cat union: the litter robot is still broken. Fix it, human servant.",
                "Alert: the bathroom for noble felines is out of order. Emergency whisker council has convened.",
                "Your cats are sharpening their claws in protest. Fix the Litterbot before the revolution begins.",
                "Litterbot is still busted. This is not a drill. Poop is pending. Proceed to maintenance.",
                "Attention: Your fluffy overlords are preparing a lawsuit. The grounds? Inaccessible bathroom facilities.",
                "If you’re hearing this, it means no one has fixed the Litterbot. Shame. Shame!"
              ] %}
              {{ nags | random }}
            data:
              type: announce
              method: all

  - repeat:
      for_each:
        - notify.mobile_app_ankit
        - notify.mobile_app_danielle
      sequence:
        - service: "{{ repeat.item }}"
          data:
            message: "💩 Litterbot is STILL busted. Cats are circling. Send help."
            title: "NAG: Fix the Litterbot"
            data:
              persistent: true
              ttl: 0
              priority: high
              tag: litterbot_nag
mode: single