alias: "Litterbot Nag Snooze Until Home Clear"
id: "litterbot_nag_snooze_until_home_clear"
trigger:
  - platform: template
    value_template: >-
      {% set target = states('input_text.litterbot_nag_snooze_until_home_person') %}
      {{ is_state('input_boolean.litterbot_nag_snooze_until_home', 'on') and
         target in states and is_state(target, 'home') }}
condition: []
action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.litterbot_nag_snooze_until_home
  - service: input_text.set_value
    target:
      entity_id: input_text.litterbot_nag_snooze_until_home_person
    data:
      value: "person.ankit_aggarwal"
mode: single
